language: java

jdk:
  - openjdk8

dist: trusty

services:
  - docker

before_install:
  - docker pull tarantool/tarantool:2.3

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip -B -V

script:
  - mvn compile
  - mvn test

notifications:
  email: false

branches:
  only:
    - master
